import React,{useState} from 'react';
import {Search,Package,Trash2,Pill,Receipt,Users,ChevronRight} from 'lucide-react';
import {Card,Top,Stat} from '../../components/Common';
import {money} from '../../utils/storage';
export function Inventory({data,setData,setModal,setTab}){return <main><Top title="Home Inventory" onBack={()=>setTab('home')}/><div className="searchbox"><Search size={18}/><input placeholder="Search items..."/></div><div className="stats"><Stat n={data.items.length} t="Total Items"/><Stat n="8" t="Expiring Soon"/><Stat n="5" t="Low Stock"/></div><div className="sectionTitle"><b>Recently Added</b><span>{data.items.length} items</span></div><Card>{data.items.map(x=><div className="row" key={x.id}><Package size={22}/><div><b>{x.name}</b><small>{x.cat} · {x.room}</small></div><button className="iconBtn" onClick={()=>setData(d=>({...d,items:d.items.filter(i=>i.id!==x.id)}))}><Trash2 size={16}/></button></div>)}</Card><button className="primary wide" onClick={()=>setModal('item')}>＋ Add Item</button></main>}
export function Medicines({data,toggleMed}){return <main><Top title="Medicines"/><div className="datebar">Sun　Mon　 <b>Tue</b>　Wed　Thu　Fri　Sat</div><h3>Today's Schedule</h3><Card>{data.meds.map(x=><div className="row" key={x.id}><Pill size={20}/><div><b>{x.name}</b><small>{x.dose}</small></div><button className={x.taken?'pill done':'pill'} onClick={()=>toggleMed(x.id)}>{x.taken?'Taken':'Mark'}</button></div>)}</Card></main>}
export function Bills({data}){return <main><Top title="Bills & Subscriptions"/><Card cls="total"><small>Total Due</small><strong>{money(data.bills.reduce((s,x)=>s+x.amount,0))}</strong><span>This Month</span></Card>{data.bills.map(x=><Card key={x.id} cls="bill"><div><b>{x.name}</b><small>{x.provider} · Due {x.due}</small></div><strong>{money(x.amount)}</strong></Card>)}</main>}
export function Expenses({data,total,setModal}){return <main><Top title="Expenses"/><Card cls="total"><small>Total Expenses</small><strong>{money(total)}</strong><span>Local data · this device</span></Card><Card><h3>Recent Transactions</h3>{data.expenses.map(x=><div className="row" key={x.id}><Receipt size={20}/><div><b>{x.name}</b><small>{x.cat}</small></div><strong>{money(x.amount)}</strong></div>)}</Card><button className="primary wide" onClick={()=>setModal('expense')}>＋ Add Expense</button></main>}
export function Family({data,setData,setModal}){const members=data.family||[];return <main><Top title="Family"/><Card cls="familyHero"><div><small>Family Members</small><strong>{members.length}</strong><span>people in your LifeOS</span></div><Users size={42}/></Card><div className="sectionTitle"><b>Members</b><span>{members.length} total</span></div>{members.map(x=><Card key={x.id} cls="memberCard"><div className="memberAvatar">{x.name.charAt(0).toUpperCase()}</div><div className="memberInfo"><b>{x.name}</b><small>{x.relationship}{x.dob?' · '+x.dob:''}</small>{x.phone&&<small>{x.phone}</small>}</div>{x.relationship!=='Self'&&<button className="iconBtn" onClick={()=>setData(d=>({...d,family:(d.family||[]).filter(m=>m.id!==x.id)}))}><Trash2 size={16}/></button>}</Card>)}<button className="primary wide" onClick={()=>setModal('family')}>＋ Add Family Member</button></main>}
export function Reminders({data}){return <main><Top title="Reminders"/>{data.tasks.map(x=><Card key={x.id} cls="bill"><div><b>{x.title}</b><small>{x.date}</small></div><ChevronRight/></Card>)}</main>}
export function Documents(){return <Placeholder title="Documents" text="Document storage is ready to connect to upload/OCR services."/>}
export function Shopping(){return <Placeholder title="Shopping List" text="Shopping list is ready as a modular Life OS feature."/>}
function Placeholder({title,text}){return <main><Top title={title}/><Card><h3>{title}</h3><p>{text}</p><button className="primary" onClick={()=>alert('This module is prepared for the next MVP iteration.')}>Add first item</button></Card></main>}
