import React from 'react';
import {ArrowRight,CheckCircle2,ShieldCheck,Users,Sparkles,Wallet,Receipt,Folder,Bell,Play} from 'lucide-react';
import PublicHeader from '../../components/PublicHeader';
import PublicFooter from '../../components/PublicFooter';
const info={
 'feature-tasks':{badge:'Tasks & Reminders',title:'Remember less. Stay ahead.',desc:'Capture tasks quickly and keep upcoming responsibilities visible.',Icon:Bell,bullets:['Quickly add tasks','Track due dates','See upcoming reminders','Keep daily responsibilities in one place']},
 'feature-bills':{badge:'Bills & Subscriptions',title:'Know what is due before it is urgent.',desc:'Bring recurring bills, amounts and renewal dates together.',Icon:Receipt,bullets:['Track monthly bills','Record amounts and due dates','Keep subscriptions visible','Add renewal reminders']},
 'feature-documents':{badge:'Documents',title:'Keep important information easier to find.',desc:'Organize documents around the parts of life they belong to.',Icon:Folder,bullets:['Store document references','Group by life area','Track expiry dates','Connect documents to reminders']},
 'feature-finance':{badge:'Finance Tracking',title:'A simpler view of everyday money.',desc:'Use fast entry for expenses and build a clear monthly picture.',Icon:Wallet,bullets:['Quick expense capture','Simple categories','Monthly totals','Designed for future bank integrations']},
 'feature-ai':{badge:'AI Life Builder',title:'Tell Life OS what you need.',desc:'Create a personal module without waiting for the product team to build every use case.',Icon:Sparkles,bullets:['Describe a tracker naturally','Preview what AI creates','Use safe predefined field types','Add the module to My Life']},
 'family-info':{badge:'For Families',title:'Shared life, less coordination.',desc:'Keep family members, dates and responsibilities in one place.',Icon:Users,bullets:['Add family members','Track birthdays and important dates','Associate reminders','Prepare for future shared access']},
 security:{badge:'Security',title:'Your life is personal.',desc:'Life OS should earn access gradually and keep users in control.',Icon:ShieldCheck,bullets:['Opt-in integrations','Minimal data collection','Encryption for production','No bank-password collection']}
};
export default function InfoPage({screen,go}){const d=info[screen]||info['feature-ai'];const Icon=d.Icon;return <div className="publicPage"><PublicHeader go={go}/><main className="infoPage"><section className="infoHero"><span className="eyebrow"><Icon size={15}/> {d.badge}</span><h1>{d.title}</h1><p>{d.desc}</p><div className="heroButtons"><button className="primary heroCta" onClick={()=>go('register')}>Get Started <ArrowRight size={17}/></button><button className="secondary" onClick={()=>go('demo')}><Play size={16}/> See Demo</button></div></section><section className="infoCard"><h2>What it helps you do</h2>{d.bullets.map(x=><div className="infoBullet" key={x}><CheckCircle2 size={19}/><span>{x}</span></div>)}</section></main><PublicFooter go={go}/></div>}
